# -*- coding: utf-8 -*-
"""ANALISIS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i4zuebeUvl6AbEtuSipe_k7gvSMYGW3e
"""

# =========================================================
# 1. IMPORT LIBRARY
# =========================================================
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from imblearn.over_sampling import SMOTE

# =========================================================
# 2. MENDEFINISIKAN PERTANYAAN BISNIS (Sesuai Urutan Alur)
# =========================================================
print("""
=================================================
             BUSINESS QUESTIONS
=================================================
1. Apakah dataset mengalami ketidakseimbangan kelas (imbalance) sebelum SMOTE?
2. Faktor klinis apa saja yang memengaruhi risiko kejadian stroke?
3. Apakah variabel usia, hipertensi, dan penyakit jantung memiliki korelasi kuat?
4. Bagaimana pengaruh distribusi BMI dan rata-rata kadar glukosa terhadap stroke?
5. Bagaimana memastikan penanganan imbalance (SMOTE) bebas dari Data Leakage?
""")

# =========================================================
# 3. GATHERING DATA
# =========================================================
df = pd.read_csv('/content/stroke_data.csv')
print("Dataset berhasil dimuat ke dalam DataFrame.")

# =========================================================
# 4. ASSESSING DATA
# =========================================================
print("\n========== INFORMASI STRUKTUR DATA (ASSESSING) ==========")
print(df.info())

print("\n========== IDENTIFIKASI MISSING VALUES ==========")
print(df.isnull().sum())

# =========================================================
# 5. CLEANING DATA , STRICT SPLITTING (ANTI-DATA LEAKAGE), DAN DATA DICTIONARY
# =========================================================
# Penanganan Missing Value Awal secara Manual
cols_to_check = ['BMI', 'Avg_Glucose']
for col in cols_to_check:
    if col in df.columns:
        df[col] = df[col].fillna(df[col].median())
print("\n Imputasi missing value awal berhasil ditangani.")

# --- Mencegah Data Leakage (Kriteria Utama) ---
# Memisahkan Fitur dan Target
X = df.drop('Stroke', axis=1)
y = df['Stroke']

print("\n Distribusi Kelas Target Awal (Imbalance Check):")
print(y.value_counts())

# Melakukan Pemisahan Data Latih & Uji di AWAL sebelum Rekayasa Fitur/SMOTE
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)
print(f"\n Strict Data Splitting Selesai. Train shape: {X_train.shape} | Test shape: {X_test.shape}")

# =========================================================
# 6. FEATURE ENGINEERING / PREPROCESSING (Terisolasi per Subset)
# =========================================================
# Salin data untuk menghindari SettingWithCopyWarning
X_train = X_train.copy()
X_test = X_test.copy()

# A. Label Encoding (Gender)
le = LabelEncoder()
X_train['Gender'] = le.fit_transform(X_train['Gender'])
X_test['Gender'] = le.transform(X_test['Gender']) # Menggunakan parameter fit dari Train Set

# B. Ordinal Encoding (SES)
ses_dict = {'Low': 0, 'Medium': 1, 'High': 2}
X_train['SES'] = X_train['SES'].map(ses_dict)
X_test['SES'] = X_test['SES'].map(ses_dict)

# C. One-Hot Encoding (Smoking_Status) - Diselaraskan kolomnya
X_train = pd.get_dummies(X_train, columns=['Smoking_Status'])
X_test = pd.get_dummies(X_test, columns=['Smoking_Status'])
X_train, X_test = X_train.align(X_test, join='left', axis=1, fill_value=0)

# D. Feature Scaling (Age, BMI, Avg_Glucose) secara Independen
scaler = StandardScaler()
num_features = ['Age', 'BMI', 'Avg_Glucose']
X_train[num_features] = scaler.fit_transform(X_train[num_features])
X_test[num_features] = scaler.transform(X_test[num_features]) # Hanya transform pada Test Set!

print("Preprocessing & Feature Scaling terisolasi selesai.")

# E. Data Dictionary
data_dict_data = {
    'Nama Fitur': [
        'Gender', 'Age', 'Hypertension', 'Heart_Disease',
        'Smoking_Status', 'Residential_Type', 'SES',
        'Avg_Glucose_Level', 'BMI', 'Stroke'
    ],
    'Tipe Data': [
        'Kategorikal (Nominal)', 'Numerik (Diskrit)', 'Kategorikal (Biner)', 'Kategorikal (Biner)',
        'Kategorikal (Nominal)', 'Kategorikal (Biner)', 'Kategorikal (Ordinal)',
        'Numerik (Kontinu)', 'Numerik (Kontinu)', 'Kategorikal (Biner)'
    ],
    'Deskripsi': [
        'Jenis kelamin dari pasien pemeriksaan.',
        'Usia pasien dalam satuan tahun.',
        'Riwayat apakah pasien menderita tekanan darah tinggi.',
        'Riwayat apakah pasien memiliki penyakit jantung.',
        'Status atau kebiasaan merokok dari pasien.',
        'Jenis lingkungan tempat tinggal atau domisili pasien.',
        'Socioeconomic Status (Status Sosial Ekonomi) pasien.',
        'Rata-rata kadar glukosa/gula di dalam darah pasien (mg/dL).',
        'Body Mass Index (Indeks Massa Tubuh) pasien (kg/m²).',
        'Status kejadian stroke (Variabel Target).'
    ],
    'Nilai / Batasan': [
        '0: Female, 1: Male',
        'Angka riil bulat (18 - 90)',
        '0: Tidak Ada, 1: Memiliki Hipertensi',
        '0: Tidak Ada, 1: Memiliki Penyakit Jantung',
        '0: Never Smoked, 1: Formerly Smoked, 2: Smokes',
        '0: Rural (Desa), 1: Urban (Kota)',
        '0: Low, 1: Medium, 2: High',
        'Angka desimal positif',
        'Angka desimal positif / NaN (sebelum imputasi)',
        '0: Tidak Stroke, 1: Terkena Stroke'
    ]
}

data_dictionary = pd.DataFrame(data_dict_data)
print("=======================================================================")
print("                      DOCUMENTATION: DATA DICTIONARY                   ")
print("=======================================================================")
display(data_dictionary)
# =========================================================
# 7. HANDLING IMBALANCE VIA SMOTE (Hanya Pada Training Set)
# =========================================================
# SMOTE diaplikasikan HANYA pada X_train dan y_train agar tidak merusak keaslian data uji
smote = SMOTE(random_state=42)
X_train_res, y_train_res = smote.fit_resample(X_train, y_train)

print("\n Penanganan Imbalance Selesai:")
print(f"Dimensi Target Train Sebelum SMOTE : \n{y_train.value_counts()}")
print(f"Dimensi Target Train Setelah SMOTE : \n{y_train_res.value_counts()}")

# Ekspor Dataset Akhir Siap Pakai (Format CSV Terstruktur)
train_final = X_train_res.copy()
train_final['Stroke'] = y_train_res
train_final.to_csv('stroke_train_clean.csv', index=False)

test_final = X_test.copy()
test_final['Stroke'] = y_test
test_final.to_csv('stroke_test_clean.csv', index=False)
print("\n Dataset akhir sukses disimpan ke format CSV terpisah (Siap Masuk Pemodelan ML!)")

# =========================================================
# 8. EXPLORATORY DATA ANALYSIS (EDA)
# =========================================================
print("\n========== DESKRIPSI DATA TRAINING MATANG (EDA) ==========")
print(train_final.describe())

# =========================================================
# 9. VISUALISASI DATA
# =========================================================
# Visualisasi 1: Distribusi Target Pasca SMOTE di Training Set
plt.figure(figsize=(6,4))
sns.countplot(x='Stroke', data=train_final, palette='Set2')
plt.title('Distribusi Target Stroke pada Train Set Pasca SMOTE')
plt.show()

# Visualisasi 2: Heatmap Korelasi Fitur Terhadap Target
plt.figure(figsize=(12,8))
sns.heatmap(train_final.corr(), annot=True, cmap='coolwarm', fmt='.2f')
plt.title('Heatmap Korelasi Matriks Data Tabular')
plt.show()

# Visualisasi 3: Distribusi Umur Standar Terhadap Kejadian Stroke
plt.figure(figsize=(8,5))
sns.boxplot(x='Stroke', y='Age', data=train_final, palette='Set3')
plt.title('Distribusi Nilai Skala Usia Berdasarkan Kejadian Stroke')
plt.show()

# =========================================================
# 10. EXPLANATORY ANALYSIS
# =========================================================
print("""
=================================================
            EXPLANATORY ANALYSIS
=================================================
1. Dataset awal terbukti mengalami ketidakseimbangan kelas (imbalance) yang signifikan, namun berhasil diseimbangkan pada subset pelatihan menggunakan metode SMOTE secara aman.
2. Berdasarkan matriks korelasi, variabel Usia (Age), Hipertensi (Hypertension), dan Penyakit Jantung (Heart_Disease) memiliki asosiasi positif tertinggi dengan risiko stroke.
3. Sebaran visual Boxplot menunjukkan pergeseran kuartil usia pasien stroke yang lebih tinggi, mengonfirmasi bahwa penuaan merupakan salah satu faktor risiko utama.
4. Nilai prapemrosesan parameter seperti pencarian median imputasi dan parameter rata-rata penskalaan StandardScaler dilakukan secara terpisah (Strict Splitting) untuk mengeliminasi celah Data Leakage.
5. Berkas akhir 'stroke_train_clean.csv' dan 'stroke_test_clean.csv' telah siap digunakan untuk melatih algoritma Machine Learning Classifier (seperti Logistic Regression, Random Forest, atau XGBoost).
""")

print("\n ANALISIS DATA STROKE SELESAI")